-- *****************************************************
-- Entidad Registro de Distrito [DISTR]
-- *****************************************************

CREATE TABLE `SistemaCT`.`DISTRITO` ( 
    `DISTRCODIGO` INT NOT NULL  AUTO_INCREMENT COMMENT 'CODIGO DE DISTRITO' ,
    `DISTRNOMBRE` VARCHAR(250) NOT NULL UNIQUE COMMENT 'NOMBRE DE DISTRITO' ,
    `PROVCODIGO` INT NOT NULL  COMMENT 'CODIGO DEL PROVINCIA' ,
    
    CONSTRAINT PK_DISTR PRIMARY KEY (`DISTRCODIGO`)

) ENGINE = INNODB CHARSET=utf8 COLLATE utf8_general_ci COMMENT = 'REGISTRO DE DISTRITO (DISTR)';


-- *****************************************************
-- Entidad Registro de Provincia [PROV]
-- *****************************************************


CREATE TABLE `sistemact`.`PROVINCIA` (
    `PROVCODIGO` INT NOT NULL  AUTO_INCREMENT COMMENT 'CODIGO DEL PROVINCIA' ,
    `PROVNOMBRE` VARCHAR(250) NOT NULL UNIQUE COMMENT 'NOMBRE DEL PROVINCIA' , 
    `PAISCODIGO` INT NOT NULL COMMENT 'CODIGO DEL PAIS' ,
    
    CONSTRAINT PK_PROV PRIMARY KEY (`PROVCODIGO`)
    
) ENGINE = INNODB CHARSET=utf8 COLLATE utf8_general_ci COMMENT = 'REGISTRO DE PROVINCIA'; 


-- *****************************************************
-- Entidad Registro de Pais [PAIS]
-- *****************************************************


CREATE TABLE `sistemact`.`PAIS` ( 
    `PAISCODIGO` INT NOT NULL  AUTO_INCREMENT COMMENT 'CODIGO DEL PAIS' ,
    `PAISNOMBRE` VARCHAR(250) NOT NULL UNIQUE COMMENT 'NOMBRE DEL PAIS' , 
    
    CONSTRAINT PK_PAIS PRIMARY KEY (`PAISCODIGO`)

) ENGINE = INNODB CHARSET=utf8 COLLATE utf8_general_ci COMMENT = 'REGISTRO DE PAIS (PAIS)'; 


-- *****************************************************
-- Entidad de Tipo de Estado [EST]
-- *****************************************************


CREATE TABLE `sistemact`.`ESTADO` ( 
    `ESTCODIGO` INT NOT NULL  AUTO_INCREMENT COMMENT 'CODIGO DEL ESTADO' , 
    `ESTDESCRIPCION` VARCHAR(250) NOT NULL COMMENT 'DESCRIPCION DEL ESTADO' ,
    `ESTTIPO` VARCHAR(250) NOT NULL  COMMENT 'TIPO DE ESTADO' , 
    
    
    CONSTRAINT PK_EST PRIMARY KEY (`ESTCODIGO`)

) ENGINE = INNODB CHARSET=utf8 COLLATE utf8_general_ci COMMENT = 'REGISTRO DE ESTADO (EST)'; 


-- *****************************************************
-- Entidad Registro de Tipo de Area  [AREA]
-- *****************************************************


CREATE TABLE `sistemact`.`AREA` ( 
    `AREACODIGO` VARCHAR(2) NOT NULL  COMMENT 'CODIGO DEL AREA' ,
    `AREADESCRIPCION` VARCHAR(250) NOT NULL UNIQUE COMMENT 'DESCRIPCION DEL AREA' , 
    
    CONSTRAINT PK_AREA PRIMARY KEY (`AREACODIGO`)

) ENGINE = INNODB CHARSET=utf8 COLLATE utf8_general_ci COMMENT = 'REGISTRO DE TIPO DE AREA'; 


-- *****************************************************
-- Entidad Registro de Familia  [FAM]
-- *****************************************************



CREATE TABLE `sistemact`.`FAMILIA` ( 
    `FAMCODIGO` VARCHAR(2) NOT NULL  COMMENT 'CODIGO DEL FAMILIA' ,
    `FAMDESCRIPCION` VARCHAR(250) NOT NULL UNIQUE COMMENT 'DESCRIPCION DEL FAMILIA' , 
    
    CONSTRAINT PK_FAM PRIMARY KEY (`FAMCODIGO`)

) ENGINE = INNODB CHARSET=utf8 COLLATE utf8_general_ci COMMENT = 'REGISTRO DEL TIPO DE FAMILIA (FAM)'; 


-- *****************************************************
-- Entidad Registro de Sub Familia  [SUBFAM]
-- *****************************************************


CREATE TABLE `sistemact`.`SUB_FAMILIA` ( 
    `SUBFAMCODIGO` VARCHAR(5) NOT NULL  COMMENT 'CODIGO DEL SUB-FAMILIA' ,
    `SUBFAMDESCRIPCION` VARCHAR(250) NOT NULL COMMENT 'DESCRIPCION DEL SUB-FAMILIA' , 
    `FAMCODIGO` VARCHAR(2) NOT NULL  COMMENT 'CODIGO DEL FAMILIA' ,
    
    CONSTRAINT PK_SUBFAM PRIMARY KEY (`SUBFAMCODIGO`)

) ENGINE = INNODB CHARSET=utf8 COLLATE utf8_general_ci COMMENT = 'REGISTRO DE TIPO DE SUB_FAMILIA (SUBFAM)'; 


-- *****************************************************
-- Entidad Registro de Impresion  [IMPREN]
-- *****************************************************


CREATE TABLE `sistemact`.`IMPRESION` ( 
    `IMPRENCODIGO` VARCHAR(3) NOT NULL  COMMENT 'CODIGO DE LA IMPRESION' ,
    `MAQUICODIGO` varchar(4) NOT NULL COMMENT 'CODIGO DE MAQUINA',
    `IMPRENCOLOR_ESPECIAL` VARCHAR(30) NOT NULL COMMENT 'COLOR DE LA IMPRESION ESPECIAL' , 
    `IMPRENBARNIZ_OFFSET` VARCHAR(30) NOT NULL COMMENT 'EL BARNIZ OFFSET SELECCIONADO' ,
    `IMPRENBARNIZ_ACRILICO` VARCHAR(30) NOT NULL COMMENT 'EL BARNIZ ACRILICO SELECCIONADO' ,
    `IMPRENOBSERVACION` VARCHAR(250) NOT NULL COMMENT 'OBSERVACIONES DE LA IMPRESION' ,
    `MODCODIGO` VARCHAR(3) NOT NULL  COMMENT 'CODIGO DEL MODELO' ,
    
    CONSTRAINT PK_IMPREN PRIMARY KEY (`IMPRENCODIGO`)

) ENGINE = INNODB CHARSET=utf8 COLLATE utf8_general_ci COMMENT = 'REGISTRO DE IMPRESION (IMPREN)'; 


-- *****************************************************
-- Entidad Registro de Presupuesto  [PRESUP]
-- *****************************************************



CREATE TABLE `sistemact`.`PRESUPUESTO` (
    `PRESUPNUMERO` VARCHAR(50) NOT NULL  COMMENT 'NUMERO DEL PRESUPUESTO' , 
    `CLIENCODIGO` int(11) NOT NULL COMMENT 'CODIGO DEL CLIENTE',
    `PRESUPFECHA_REGISTRO` DATE NOT NULL COMMENT 'FECHA QUE SE REGISTRO EL PEDIDO' , 
    `ESTCODIGO` INT NOT NULL  COMMENT 'CODIGO DEL ESTADO' , 
    `PRESUPVENDEDOR` VARCHAR(20) NOT NULL  COMMENT 'NOMBRE DEL VENDEDOR' , 
    `PRESUPCANT_ITEM` INT NOT NULL  COMMENT 'CANTIDAD DE ITEMS' , 
    
    CONSTRAINT PK_PRESUP PRIMARY KEY (`PRESUPNUMERO`)

) ENGINE = INNODB CHARSET=utf8 COLLATE utf8_general_ci COMMENT = 'REGISTRO DE PRESUPUESTO (PRESUP)'; 


-- *****************************************************
-- Entidad Registro de Item Presupuesto  [ITPRESU]
-- *****************************************************



CREATE TABLE `sistemact`.`ITEM_PRESUPUESTO` (
    `ITPRESUCODIGO` VARCHAR(20) NOT NULL  COMMENT 'CODIGO DEL ITEM DEL PRESUPUESTO' ,
    `ITPRESUDESCRIPCION` VARCHAR(250) NOT NULL  COMMENT 'DESCRIPCION DEL ITEM DEL PRESUPUESTO' ,
    `ITPRESUIMPORTE` VARCHAR(11) NOT NULL COMMENT 'IMPORTE DEL PRESUPUESTO', 
    `DETPRESUPCODIGO` VARCHAR(20) NOT NULL  COMMENT 'CODIGO DEL DETALLE PRESUPUESTO' , 
    `PRECIOPRESUPCODIGO` VARCHAR(20) NOT NULL  COMMENT 'CODIGO DEL PRECIO PRESUPUESTO' ,
    `PRESUPNUMERO` VARCHAR(50) NOT NULL  COMMENT 'NUMERO DEL PRESUPUESTO', 
    
    CONSTRAINT PK_ITPRESU PRIMARY KEY (`ITPRESUCODIGO`)

) ENGINE = INNODB CHARSET=utf8 COLLATE utf8_general_ci COMMENT = 'REGISTRO DE ITEM PRESUPUESTO (ITPRESU)'; 



-- *****************************************************
-- Entidad Registro de Detalles Presupuesto  [DETPRESUP]
-- *****************************************************



CREATE TABLE `sistemact`.`DETALLE_PRESUPUESTO` (
    `DETPRESUPCODIGO` VARCHAR(20) NOT NULL  COMMENT 'CODIGO DEL DETALLE PRESUPUESTO' ,
    `DETPRESUPMAQ` VARCHAR(4) NOT NULL  COMMENT 'MAQUINA DEL PRESUPUESTO' ,
    `DETPRESUPTIPO_PLIEGO` VARCHAR(20) NOT NULL  COMMENT 'TAMAÑO DEL PLIEGO DE MAQUINA DEL PRESUPUESTO' ,
    `DETPRESUPNUM_PM` INT NULL  COMMENT 'NUMERO DEL PLIEGO/MAQUINA X HOJA RESMA DEL PRESUPUESTO' ,
    `DETPRESUPTIRAJE_TOTAL` INT NOT NULL  COMMENT 'CANTIDAD DE TIRAJE TOTAL DE PIEZAS GRAFICAS' ,
    `DETPRESUPPIEZAS_GRAFICAS` INT NOT NULL  COMMENT 'CANTIDAD DE PIEZAS GRAFICAS' ,
    `DETPRESUPNUM_PLIEGO` INT NOT NULL  COMMENT 'CANTIDAD DE PLIEGOS' ,
    `DETPRESUPTIPO_IMPRESION` VARCHAR(20) NOT  NULL  COMMENT 'TIPO DE IMPRESION' ,
    `DETPRESUPNUM_COLOR` INT NOT  NULL  COMMENT 'CANTIDAD DE COLORES' ,
    `DETPRESUPTIP_PAPEL`  VARCHAR(20) NOT  NULL  COMMENT 'TIPO DE PAPEL' ,
    `DETPRESUPQUALITY`  VARCHAR(20) NOT  NULL  COMMENT 'RESPUESTA DE USO DE PAPEL QUALITY PAPER' ,
    `DETPRESUPCONTRATO`  VARCHAR(2) NOT  NULL  COMMENT 'RESPUESTA DE CONTRATO MARCO PARA TELEFONICA' ,
    `DETPRESUPGRAMAJE`  INT   NULL  COMMENT 'CANTIDAD DE GRAMAJE DE PAPEL' ,
    `DETPRESUPTAMAÑO_PAPEL`  decimal(10,5)  NULL  COMMENT 'TAMAÑO DEL PAPEL' ,
    `DETPRESUPPRUEBA`  VARCHAR(2) NOT  NULL  COMMENT 'RESPUESTA DE PRUEBA DE COLOR' ,
    `DETPRESUPMENSAJERIA`  VARCHAR(2) NOT  NULL  COMMENT 'RESPUESTA DE MENSAJERIA' ,
    `DETPRESUPBARNIZ_PLASTI`  VARCHAR(40)  NULL  COMMENT 'TIPO DE BARNIZADO O PLASTIFICADO' ,
    `DETPRESUPBARNIZ_PLASTI1`  VARCHAR(40)  NULL  COMMENT 'TIPO ADICIONAL 1 DE BARNIZADO O PLASTIFICADO' ,
    `DETPRESUPBARNIZ_PLASTI2`  VARCHAR(40)  NULL  COMMENT 'TIPO ADICIONAL 2 DE BARNIZADO O PLASTIFICADO' ,
    `DETPRESUPTROQUEL`  VARCHAR(10)  NULL  COMMENT 'TIPO DE TROQUELADO' ,
    `DETPRESUPDOBLADO_ALCE`  VARCHAR(20)  NULL  COMMENT 'TIPO DE DOBLADO O ALCE' ,
    `DETPRESUPCOSIDO_COLA_GRAPA`  VARCHAR(20)  NULL  COMMENT 'TIPO DE COSIDO HILO, ENCOLADO O ENGRAPADO' ,
    `DETPRESUPCAJA_PAQUETE`  VARCHAR(20)  NULL  COMMENT 'TIPO DE EMPAQUETADO O ENCAJONADO' ,
    `DETPRESUPCOSTO_PLASTICO` decimal(10,5)  NULL  COMMENT 'COSTO DEL PLASTICO' ,
    `DETPRESUPCOSTO_SERV_PLASTIFICADO` decimal(10,5) NULL COMMENT 'COSTO DEL SERVICIO DE PLASTIFICADO' ,
    `DETPRESUPCOSTO_CAJA` decimal(10,5) NULL COMMENT 'COSTO ADICIONAL X CAJAS' ,
    `DETPRESUPCOSTO_COLA_FORRO` decimal(10,5) NULL COMMENT 'COSTO DE ENCOLADO Y FORRADO' ,
    `DETPRESUPCOSTO_CORTE` decimal(10,5) NULL COMMENT 'COSTO DE DEGOLLADO Y CORTE' ,
    `DETPRESUPCOSTO_ARMADO` decimal(10,5) NULL COMMENT 'COSTO DE ARMADO Y PEGADO DE BOLSILLO' ,
    `DETPRESUPCOSTO_OJAL` decimal(10,5) NULL COMMENT 'COSTO DE PUESTA DE OJALILLO' ,
    `DETPRESUPCOSTO_NYLON` decimal(10,5) NULL COMMENT 'COSTO DE NYLON',
    `DETPRESUPCOSTO_PNYLON` decimal(10,5) NULL COMMENT 'COSTO DE PUESTA DE NYLON',

    
    CONSTRAINT PK_DETPRESUP PRIMARY KEY (`DETPRESUPCODIGO`)

) ENGINE = INNODB CHARSET=utf8 COLLATE utf8_general_ci COMMENT = 'REGISTRO DE DETALLE PRESUPUESTO (DETPRESUP)'; 


-- *****************************************************
-- Entidad Registro de Precio Presupuesto  [PRECIOPRESUP]
-- *****************************************************


CREATE TABLE `sistemact`.`PRECIO_PRESUPUESTO` (
    `PRECIOPRESUPCODIGO` VARCHAR(20) NOT NULL  COMMENT 'CODIGO DEL PRECIO PRESUPUESTO' ,
    `PRECIOPRESUPDOLAR` VARCHAR(20) NOT NULL  COMMENT 'PRECIO DEL PRESUPUESTO EN DOLAR' ,
    `PRECIOPRESUPSOLES` VARCHAR(20) NOT NULL  COMMENT 'PRECIO DEL PRESUPUESTO EN SOLES' ,
    `PRECIOPRESUPXMILLAR` VARCHAR(20) NOT NULL  COMMENT 'PRECIO DEL PRESUPUESTO POR MILLAR' ,
    `PRECIOPRESUPUNITARIO` VARCHAR(20) NOT NULL  COMMENT 'PRECIO DEL PRESUPUESTO UNITARIO' ,
    `PRECIOPRESUPXPAQUETE` VARCHAR(20) NOT NULL  COMMENT 'PRECIO DEL PRESUPUESTO X PAQUETE 500 HOJAS' ,
    `PRECIOPRESUP18010_DOLAR` VARCHAR(20) NOT NULL  COMMENT 'RANGO DE PRECIO F1810 EN DOLAR' ,
    `PRECIOPRESUP18010_SOLES` VARCHAR(20) NOT NULL  COMMENT 'RANGO DE PRECIO F1810 EN SOLES' ,
    `PRECIOPRESUPNORMAL_DOLAR` VARCHAR(20) NOT NULL  COMMENT 'RANGO DE PRECIO NORMAL EN DOLAR' ,
    `PRECIOPRESUPNORMAL_SOLES` VARCHAR(20) NOT NULL  COMMENT 'RANGO DE PRECIO NORMAL EN SOLES' ,
    `PRECIOPRESUPINSUMOS` VARCHAR(20) NOT NULL  COMMENT 'PRECIO DE INSUMOS' ,
    `PRECIOPRESUPTALLERRES` VARCHAR(20) NOT NULL  COMMENT 'PRECIO DE TALLERES' ,
    `PRECIOPRESUPFLETE` VARCHAR(20) NOT NULL  COMMENT 'PRECIO DE EMB/FLETE' ,
    `PRECIOPRESUPGASTOS` VARCHAR(20) NOT NULL  COMMENT 'PRECIO DE GASTOS GENERALES' ,
    `PRECIOPRESUPMARGEN` VARCHAR(20) NOT NULL  COMMENT 'PRECIO DE MARGEN' ,
    `PRECIOPRESUPNETO` VARCHAR(20) NOT NULL  COMMENT 'PRECIO TOTAL NETO' ,
    `PRECIOPRESUPIMPUESTO` VARCHAR(20) NOT NULL  COMMENT 'PRECIO DE IMPUESTO' ,
    `PRECIOPRESUPTOTAL` VARCHAR(20) NOT NULL  COMMENT 'PRECIO TOTAL' ,
    `PRECIOPRESUPUNITARIO_I` VARCHAR(20) NOT NULL  COMMENT 'PRECIO UNITARIO CON IMPUESTO' ,

    
    CONSTRAINT PK_PRECIOPRESUP PRIMARY KEY (`PRECIOPRESUPCODIGO`)

) ENGINE = INNODB CHARSET=utf8 COLLATE utf8_general_ci COMMENT = 'REGISTRO DE PRECIO PRESUPUESTO (PRECIOPRESUP)'; 


-- *****************************************************
-- Entidad Registro de Modelo  [MOD]
-- *****************************************************


CREATE TABLE `sistemact`.`MODELO` ( 
    `MODCODIGO` VARCHAR(3) NOT NULL  COMMENT 'CODIGO DEL MODELO' ,
    `MODTAMAÑO_PLIEGO` VARCHAR(15) NOT NULL COMMENT 'TAMAÑO DE PLIEGO' ,
    `MODNUMERO_PLIEGO` VARCHAR(250) NOT NULL COMMENT 'NUMERO DE PLIEGOS' ,
    `MODNUMERO_PLACA` VARCHAR(250) NOT NULL COMMENT 'NUMERO DE PLACAS' ,
    `MODPINZA` VARCHAR(20) NOT NULL COMMENT 'MEDIDA DE LA PINZA DEL MODELO' ,
    `MODIMAGEN1` VARCHAR(250) NOT NULL COMMENT 'IMAGEN DEL MODELO 1' , 
    `MODIMAGEN2` VARCHAR(250) NULL COMMENT 'IMAGEN DEL MODELO 2' ,
    `MODINDICACIONES` VARCHAR(250) NULL COMMENT 'INDICACIONES DEL MODELO' , 
    
    CONSTRAINT PK_MOD PRIMARY KEY (`MODCODIGO`)

) ENGINE = INNODB CHARSET=utf8 COLLATE utf8_general_ci COMMENT = 'REGISTRO DE MODELO (MOD)'; 



-- *****************************************************
-- Entidad Registro de Detalles Acabado [DETACAB]
-- *****************************************************


CREATE TABLE `sistemact`.`DETALLES_ACABADO` (
    `DETACABCODIGO` VARCHAR(3) NOT NULL  COMMENT 'CODIGO DEL DETALLE ACABADO' ,
    `DETACABTIPO_BARNIZADO` VARCHAR(50)  NULL COMMENT 'TIPO DE BARNIZ DEL ACABADO' , 
    `DETACABTIPO_PLASTIFICADO` VARCHAR(50)  NULL COMMENT 'TIPO DE PLASTIFICADO DEL ACABADO' , 
    `DETACABTIPO_TROQUELADO` VARCHAR(50)  NULL COMMENT 'TIPO DE TROQUELADO DEL ACABADO' , 
    `DETACABTIPO_DOBLEZ` VARCHAR(50)  NULL COMMENT 'TIPO DE DOBLES DEL ACABADO' ,
    `DETACABTIPO_COMPAGINADO` VARCHAR(50)  NULL COMMENT 'TIPO DE COMPAGINADO DEL ACABADO' ,
    `DETACABTIPO_ENCOLADO` VARCHAR(50)  NULL COMMENT 'TIPO DE ENCOLADO DEL ACABADO' , 
    `DETACABTIPO_PERFORADO` VARCHAR(50)  NULL COMMENT 'TIPO DE PERFORADO DEL ACABADO' , 
    `DETACABTIPO_CORTE` VARCHAR(50)  NULL COMMENT 'TIPO DE CORTE DEL ACABADO' , 
    `DETACABTIPO_FAJILLADO` VARCHAR(50)  NULL COMMENT 'TIPO DE FAJILLADO DEL ACABADO' , 
    `DETACABTIPO_CONTADO` VARCHAR(50)  NULL COMMENT 'TIPO DE CONTADO DEL ACABADO' , 
    `DETACABTIPO_NUMERADO` VARCHAR(50)  NULL COMMENT 'TIPO DE NUMERADO DEL ACABADO' , 
    `DETACABTIPO_PEGADO` VARCHAR(50)  NULL COMMENT 'TIPO DE PEGADO DEL ACABADO' , 
    `DETACABTIPO_CONTRAPLACADO` VARCHAR(50)  NULL COMMENT 'TIPO DE CONTRAPLACADO DEL ACABADO' , 
    `DETACABTIPO_REFILADO` VARCHAR(50)  NULL COMMENT 'TIPO DE REFILADO DEL ACABADO' , 
    `DETACABTIPOOTROS1` VARCHAR(50)  NULL COMMENT 'OTROS 1' , 
    `DETACABTIPOOTROS2` VARCHAR(50)  NULL COMMENT 'OTROS 2' , 
    `DETACABTIPOOTROS3` VARCHAR(50)  NULL COMMENT 'OTROS 3' ,  
    
    CONSTRAINT PK_DETACAB PRIMARY KEY (`DETACABCODIGO`)

) ENGINE = INNODB CHARSET=utf8 COLLATE utf8_general_ci COMMENT = 'REGISTRO DE DETALLE ACABADO (DETACAB)'; 


-- *****************************************************
-- Entidad Registro de Orden de Papel  [OPA]
-- *****************************************************



CREATE TABLE `sistemact`.`ORDEN_PAPEL` ( 
    `OPACODIGO` INT NOT NULL  AUTO_INCREMENT COMMENT 'CODIGO DE LA ORDEN DE PAPEL' ,
    `OPAMATERIAL` VARCHAR(250) NOT NULL COMMENT 'MATERIAL DE LA ORDEN DE PAPEL' ,
    `OPAGRAMOS` INT NOT NULL COMMENT 'CANTIDAD DE GRAMOS DE LA ORDEN DE PAPEL' , 
    `OPAHOJA_RESMA` VARCHAR(250) NOT NULL COMMENT 'HOJA RESMA DE LA ORDEN DE PAPEL' , 
    `OPAMEDIDA_RESMA` VARCHAR(250) NOT NULL COMMENT 'MEDIDA RESMA DE LA ORDEN DE PAPEL' , 
    `OPAMEDIDA_CORTE` VARCHAR(250) NOT NULL COMMENT 'MEDIDA DE CORTE DE LA ORDEN DE PAPEL' , 
    `OPAPLIEGO_HOJA` INT NOT NULL COMMENT 'PLIEGO DE HOJAS DE LA ORDEN DE PAPEL' , 
    `OPAPANNEAU` INT NOT NULL COMMENT 'MEDIDA DEL PANNEAU' , 
    
    CONSTRAINT PK_OPA PRIMARY KEY (`OPACODIGO`)

) ENGINE = INNODB CHARSET=utf8 COLLATE utf8_general_ci COMMENT = 'REGISTRO DE ORDEN DE PAPEL (OPA)'; 



-- *****************************************************
-- Entidad Registro de Detalles del Pliego  [DETPLIE]
-- *****************************************************


CREATE TABLE `sistemact`.`DETALLES_PLIEGO` ( 
    `DETPLIENUMERO` VARCHAR(3) NOT NULL COMMENT 'NUMERO DE DETALLE DEL PLIEGO' , 
    `DETPLIEDESCRIPCION` VARCHAR(250) NOT NULL COMMENT 'DESCRIPCION DE DETALLES DE PLIEGO ' , 
    `DETPLIEMED_MAQUINA` VARCHAR(250) NOT NULL COMMENT 'MEDIDA DEL PLIEGO POR MAQUINA' , 
    `DETPLIECANT_MAQUINA` INT NOT NULL COMMENT 'CANTIDAD DE PLIEGOS POR MAQUINA' , 
    `DETPLIEDEMASIA_MAQUINA` INT NOT NULL COMMENT 'CANTIDAD DE DEMASIA DE PLIEGO POR MAQUINA' , 
    `DETPLIETOTAL_PAPEL_ENTREGADO` INT NOT NULL COMMENT 'CANTIDAD DE TOTAL DE PAPEL ENTREGADO' ,
    `DETPLIETOTAL_HOJA_RESMA` INT NOT NULL COMMENT 'CANTIDAD DE TOTAL DE HOJA RESMA' ,
    `OPACODIGO` INT NOT NULL COMMENT 'CODIGO DE LA ORDEN DE PAPEL' ,
    `IMPRENCODIGO` VARCHAR(3) NOT NULL  COMMENT 'CODIGO DE LA IMPRESION' ,
    
    CONSTRAINT PK_DETPLIE PRIMARY KEY (`DETPLIENUMERO`)

) ENGINE = INNODB CHARSET=utf8 COLLATE utf8_general_ci COMMENT = 'REGISTRO DE DETALLES DEL PLIEGO (DETPLIE)'; 



-- *****************************************************
-- Entidad Registro de Pre Prensa  [P_PREN]
-- *****************************************************



CREATE TABLE `sistemact`.`PRE_PRENSA` (
    `PPRENCODIGO` VARCHAR(3) NOT NULL  COMMENT 'CODIGO DE LA PRE PRENSA' ,
    `PPRENPRUEBA_COLOR` VARCHAR(3) NOT NULL COMMENT 'RESPUESTA DE PRUEBA DE COLOR' ,
    `PPRENMACHOTE` VARCHAR(3) NOT NULL COMMENT 'RESPUESTA DE MACHOTE' ,
    `PPRENLASER_BN` VARCHAR(3) NOT NULL COMMENT 'RESPUESTA DE MlASER BLANCO Y NEGRO',
    `PPRENFORMATO_ABIERTO` VARCHAR(30) NOT NULL COMMENT 'DETALLE DEL FORMATO ABIERTO' ,
    `PPRENFORMATO_CERRADO` VARCHAR(30) NOT NULL COMMENT 'DETALLE DEL FORMATO CERRADO' ,
    `PPRENCANTIDAD_COLOR` INT NOT NULL COMMENT 'CANTIDAD DE COLORES' ,
    `PPRENDESCRIPCION_COLOR` VARCHAR(40) NOT NULL COMMENT 'DESCRIPCION DEL COLOR NORMAL - ESPECIAL' ,
    `PPRE_LPI` INT NOT NULL COMMENT 'NUMERO DE LPI' ,
    `PPRENTIPO_IMPRESION` VARCHAR(30) NOT NULL COMMENT 'TIPO DE IMPRESION' ,
    `IMPRENCODIGO` VARCHAR(3) NOT NULL COMMENT 'CODIGO DE LA IMPRESION' ,
    
    CONSTRAINT PK_P_PREN PRIMARY KEY (`PPRENCODIGO`)

) ENGINE = INNODB CHARSET=utf8 COLLATE utf8_general_ci COMMENT = 'REGISTRO DE PRE PRENSA (P_PREN)'; 



-- *****************************************************
-- Entidad Registro de Orden de Produccion  [OP]
-- *****************************************************



CREATE TABLE `sistemact`.`ORDEN_PRODUCCION` (
    `OPCODIGO` INT NOT NULL  COMMENT 'CODIGO DE LA ORDEN DE PRODUCCION' ,
    `OPVENDEDOR` VARCHAR(60) NOT NULL COMMENT 'VENDEDOR DE LA ORDEN DE PRODUCCION' , 
    `OPNUM_ITEM` INT NOT NULL COMMENT 'NUMERO DE ITEMS DE LA ORDEN DE PRODUCCION' , 
    `ESTCODIGO` INT NOT NULL COMMENT 'CODIGO DEL ESTADO' , 
    `PRESUPNUMERO` VARCHAR(50) NOT NULL  COMMENT 'NUMERO DEL PRESUPUESTO' , 
    
    CONSTRAINT PK_OP PRIMARY KEY (`OPCODIGO`)

) ENGINE = INNODB CHARSET=utf8 COLLATE utf8_general_ci COMMENT = 'REGISTRO DE ORDEN DE PRODUCCION (OP)'; 




-- *****************************************************
-- Entidad Registro de Area de Maquina  [AREAMAQ]
-- *****************************************************



CREATE TABLE `sistemact`.`AREA_MAQUINA` (
    `AREAMAQCODIGO` VARCHAR(5) NOT NULL  COMMENT 'CODIGO DEL AREA DE MAQUINA' ,
    `AREAMAQDESCRIPCION` VARCHAR(250) NOT NULL UNIQUE COMMENT 'DESCRIPCION DE AREA DE MAQUINA' , 
    
    CONSTRAINT PK_AREAMAQ PRIMARY KEY (`AREAMAQCODIGO`)

) ENGINE = INNODB CHARSET=utf8 COLLATE utf8_general_ci COMMENT = 'REGISTRO DE AREA DE MAQUINA (AREAMAQ)'; 




-- *****************************************************
-- Entidad Registro de Costos en Acabado  [COSTACA]
-- *****************************************************


CREATE TABLE `sistemact`.`COSTOS_ACABADO` (
    `COSTACACODIGO` INT NOT NULL AUTO_INCREMENT  COMMENT 'CODIGO DE COSTOS ACABADOS' , 
    `CRINSCODIGO` VARCHAR(10) NOT NULL  COMMENT 'CODIGO DEL CONTROL DE INSUMOS' , 
    `COSTACAFECHA_REGISTRO` DATE NOT NULL COMMENT 'FECHA DE REGISTRO' , 
    `TIPACABCODIGO` VARCHAR(5) NOT NULL COMMENT 'CODIGO DEL TIPO DE ACABADO' ,
    `PERSCODIGO` INT NOT NULL COMMENT 'CODIGO DEL PERSONAL' , 
    `COSTACAFECHA_INICIO` DATE NOT NULL COMMENT 'FECHA DE INICIO' , 
    `COSTACAFECHA_FINAL` DATE NOT NULL COMMENT 'FECHA FINAL' , 
    `COSTACAOBSERVACION` VARCHAR(250) NULL COMMENT 'OBSERVACIONES' , 
    `COSTACACOSTO` DECIMAL(10,3) NOT NULL COMMENT 'COSTO DE ACABADOS' , 
    `USUACODIGO` varchar(4) NOT NULL COMMENT 'CODIGO DE USUARIO' ,
    
    CONSTRAINT PK_COSTACA PRIMARY KEY (`COSTACACODIGO`)

) ENGINE = INNODB CHARSET=utf8 COLLATE utf8_general_ci COMMENT = 'REGISTRO DE COSTO EN ACABADO (COSTACA)'; 


-- *****************************************************
-- Entidad Registro de Costo de Maquina  [COSTMAQ]
-- *****************************************************



CREATE TABLE `sistemact`.`COSTOS_MAQUINA` (
    `COSTMAQCODIGO` INT NOT NULL  AUTO_INCREMENT COMMENT 'CODIGO DE COSTOS MAQUINAS' , 
    `CRINSCODIGO` VARCHAR(10) NOT NULL  COMMENT 'CODIGO DEL CONTROL DE INSUMOS' , 
    `MAQUICODIGO` VARCHAR(4) NOT NULL COMMENT 'CODIGO DE MAQUINA' ,
    `COSTMAQFECHA_REGISTRO` VARCHAR(250) NOT NULL COMMENT 'FECHA DE REGISTRO ' ,
    `COSTMAQCOD_PER_MAQUI` INT NOT NULL COMMENT 'CODIGO DEL PERSONAL MAQUINISTA' ,
    `COSTMAQCOD_PER_AYUDANTE` INT NOT NULL COMMENT 'CODIGO DEL PERSONAL AYUDANTE' ,
    `COSTMAQTIPTRABAJO` VARCHAR(50) NOT NULL COMMENT 'TIPO DE TRABAJO DE MAQUINA' ,
    `COSTMAQFECHA_INICIO` DATE NOT NULL COMMENT 'FECHA DE INICIO' , 
    `COSTMAQFECHA_FINAL` DATE NOT NULL COMMENT 'FECHA FINAL' , 
    `COSTMAQCOSTO` DECIMAL(10,3) NOT NULL COMMENT 'COSTO DE MAQUINAS' , 
    `COSTMAQOBSERVACION` VARCHAR(250) NULL COMMENT 'OBSERVACIONES' , 
    `USUACODIGO` varchar(4) NOT NULL COMMENT 'CODIGO DE USUARIO' ,
    
    CONSTRAINT PK_COSTMAQ PRIMARY KEY (`COSTMAQCODIGO`)

) ENGINE = INNODB CHARSET=utf8 COLLATE utf8_general_ci COMMENT = 'REGISTRO DE COSTOS EN MAQUINA (COSTMAQ)'; 




-- *****************************************************
-- Entidad Registro de Control de Insumo [CRINS]
-- *****************************************************



CREATE TABLE `sistemact`.`CONTROL_INSUMO` ( 
    `CRINSCODIGO` VARCHAR(10) NOT NULL  COMMENT 'CODIGO DEL CONTROL DE INSUMO' ,
    `OPCODIGO` INT NOT NULL COMMENT 'CODIGO DE LA ORDEN DE PRODUCCION' , 
    `CRINSPRE_PRENSA` DECIMAL(10,3) NOT NULL COMMENT 'PRECIO PRE PRENSA' , 
    `CRINSPLACAS` DECIMAL(10,3) NOT NULL COMMENT 'PRECIO PLACAS' ,
    `CRINSPAPEL` DECIMAL(10,3) NOT NULL COMMENT 'PRECIO PAPEL' , 
    `CRINSTINTA` DECIMAL(10,3) NOT NULL COMMENT 'PRECIO TINTA' ,
    `CRINSIMPRESION` DECIMAL(10,3) NOT NULL COMMENT 'PRECIO IMPRESION' , 
    `CRINSMANO_OBRA` DECIMAL(10,3) NOT NULL COMMENT 'PRECIO MANO DE OBRA' , 
    `CRINSCORTE` DECIMAL(10,3) NOT NULL COMMENT 'PRECIO CORTE' ,
    `CRINSTROQUELADO` DECIMAL(10,3) NOT NULL COMMENT 'PRECIO TROQUELADO' ,
    `CRINSDOBLEZ` DECIMAL(10,3) NOT NULL COMMENT 'PRECIO DOBLEZ' , 
    `CRINSALCE` DECIMAL(10,3) NOT NULL COMMENT 'PRECIO ALCE' ,
    `CRINSBARNIZADO` DECIMAL(10,3) NOT NULL COMMENT 'PRECIO BARZINADO' ,
    `CRINSCONTADO` DECIMAL(10,3) NOT NULL COMMENT 'PRECIO CONTADO' ,
    `CRINSCONTRAPLACADO` DECIMAL(10,3) NOT NULL COMMENT 'PRECIO CONTRAPLACADO' , 
    `CRINSENCOLADO` DECIMAL(10,3) NOT NULL COMMENT 'PRECIO ENCOLADO' ,
    `CRINSDESGLOZADO` DECIMAL(10,3) NOT NULL COMMENT 'PRECIO DESGLOZADO' , 
    `CRINSENGRAPADO` DECIMAL(10,3) NOT NULL COMMENT 'PRECIO ENGRAPADO' , 
    `CRINSPEGADO` DECIMAL(10,3) NOT NULL COMMENT 'PRECIO PEGADO' ,
    `CRINSNUMERADO` DECIMAL(10,3) NOT NULL COMMENT 'PRECIO NUMERADO' , 
    `CRINSPLASTIFICADO` DECIMAL(10,3) NOT NULL COMMENT 'PRECIO PLASTIFICADO' , 
    `CRINSFAJILLADO` DECIMAL(10,3) NOT NULL COMMENT 'PRECIO FAJILADO' , 
    `CRINSEMPAQUETADO` DECIMAL(10,3) NOT NULL COMMENT 'PRECIO EMPAQUETADO' , 
    `CRINSACABADO_EXTRA` DECIMAL(10,3) NOT NULL COMMENT 'PRECIO ACABADOS EXTRAS' , 
    `CRINSSUPERVISION` DECIMAL(10,3) NOT NULL COMMENT 'PRECIO SUPERVISION' , 
    `CRINSOTROS` DECIMAL(10,3) NOT NULL COMMENT 'PRECIO OTROS' , 
    `CRINSMOVILIDAD` DECIMAL(10,3) NOT NULL COMMENT 'PRECIO MOVILIDAD' , 
    `CRINSENERGIA_ELECTRICA` DECIMAL(10,3) NOT NULL COMMENT 'PRECIO ENERGIA ELECTRICA' ,
    `CRINSPRECIO_TOTAL` DECIMAL(10,3) NOT NULL COMMENT 'PRECIO DEL COSTO TOTAL' ,
    `CRINSVALOR_VENTA` DECIMAL(10,3) NOT NULL COMMENT 'PRECIO DEL VALOR VENTA' , 
    `CRINSPORCENTAJE` VARCHAR(15) NOT NULL COMMENT 'VALOR DEL PORCENTAJE' ,
    
    CONSTRAINT PK_CRINS PRIMARY KEY (`CRINSCODIGO`)


) ENGINE = INNODB CHARSET=utf8 COLLATE utf8_general_ci COMMENT = 'REGISTRO DEL CONTROL DE INSUMO (CRINS)'; 



-- *****************************************************
-- Entidad Registro de Programacion de Maquina [PROMA]
-- *****************************************************



CREATE TABLE `sistemact`.`PROGRAMAR_MAQUINA` ( 
    `PROMACODIGO` VARCHAR(10) NOT NULL  COMMENT 'CODIGO DE PROGRAMAR MAQUINA' , 
    `PROMAFECHA_PROGRA` VARCHAR(250) NOT NULL COMMENT 'FECHA PROGRAMADA' ,
    `PROMACANTIDAD_HORAS` TIME NULL COMMENT 'CANTIDAD DE HORAS' ,
    `OPCODIGO` INT NOT NULL COMMENT 'CODIGO DE LA ORDEN DE PRODUCCION' , 
    `MAQUICODIGO` VARCHAR(4) NOT NULL COMMENT 'CODIGO DE LA MAQUINA' , 
    `PROMAOBSERVACION` VARCHAR(250) NULL COMMENT 'OBSERVACION' ,
    
    CONSTRAINT PK_PROMA PRIMARY KEY (`PROMACODIGO`)

) ENGINE = INNODB CHARSET=utf8 COLLATE utf8_general_ci COMMENT = 'REGISTRO DE PROGRAMACION DE MAQUINA (PROMA)'; 



-- *****************************************************
-- Entidad Registro de Tipo de Acabado  [TIPACAB]
-- *****************************************************


CREATE TABLE `sistemact`.`TIPO_ACABADO` ( 
    `TIPACABCODIGO` VARCHAR(5) NOT NULL  COMMENT 'CODIGO DEL TIPO DE ACABADO' , 
    `TIPACABNOMBRE` VARCHAR(250) NOT NULL COMMENT 'NOMBRE DE TIPO DE ACABADO' , 
    `TIPACABCOSTO` DECIMAL(10,3) NOT NULL COMMENT 'COSTO DE TIPO DE ACABADO' , 
    
    CONSTRAINT PK_TIPACABA PRIMARY KEY (`TIPACABCODIGO`)

) ENGINE = INNODB CHARSET=utf8 COLLATE utf8_general_ci COMMENT = 'REGISTRO DE TIPO DE ACABADO (TIPACAB)'; 


-- *****************************************************
-- Entidad Registro de Tabla F1810 MAQUINA  [FMAQUI]
-- *****************************************************


CREATE TABLE `sistemact`.`F1810_MAQUI` ( 
    `FMAQUICODIGO` INT NOT NULL AUTO_INCREMENT COMMENT 'CODIGO DE LA FORMULA F1810 MAQUINA' , 
    `USUACODIGO` varchar(4) NOT NULL COMMENT 'CODIGO DEL USUARIO DE ACTUALIZACION' , 
    `FMAQUIFECHA_MODIFICADO` DATE NOT NULL COMMENT 'FECHA DE MODIFICACION DE LA FORMULA' , 
    `FMAQUICAMBIO` DECIMAL(10,3) NOT NULL COMMENT 'TIPO DE CAMBIO' , 
    `FMAQUIHRS_OPERARIO` INT NOT NULL COMMENT 'HORAS MENSUALES DE UN OPERARIO' , 
    `FMAQUIHRS_MAQUIAUX` INT NOT NULL COMMENT 'HORAS MENSUALES DE MAQUINA AUXILIAR' , 
    `FMAQUIHRS_MAQUIIMPRE` INT NOT NULL COMMENT 'HORAS MENSUALES DE MAQUINA IMPRESORA' , 
    `FMAQUIHRS_EXTRAS` INT NOT NULL COMMENT 'HORAS EXTRAS DOBLES' , 
    `FMAQUIDECIMAL_1` DECIMAL(10,3) NOT NULL COMMENT 'DECIMAL AGREGADO 1' , 
    `FMAQUIDECIMAL_2` DECIMAL(10,3) NOT NULL COMMENT 'DECIMAL AGREGADO 2' , 
    `FMAQUISUPERVISOR`INT NOT NULL COMMENT 'SUPERVISOR PRECIO',
    `FMAQUICPOS_R700` INT NOT NULL COMMENT 'CPOS-ROLAND700' , 
    `FMAQUICPOS_SM` INT NOT NULL COMMENT 'CPOS-SPEED MASTER' , 
    `FMAQUICPOS_GTO` INT NOT NULL COMMENT 'CPOS-GTO' , 
    `FMAQUICPOS_TOTAL` INT NOT NULL COMMENT 'CPOS-TOTAL' , 
    `FMAQUIAGREGADO1` DECIMAL(10,4) NOT NULL COMMENT 'PRECIO POR HORA - AGREGADO 1' , 
    `FMAQUIAGREGADO2` DECIMAL(10,4) NOT NULL COMMENT 'PRECIO POR HORA - AGREGADO 2' , 
    `FMAQUICOSTO_TINTA72` DECIMAL(10,4) NOT NULL COMMENT 'COSTO DE TINTA PARA 1 MILLAR 72*102' ,  
    `FMAQUICOSTO_TINTA61` DECIMAL(10,4) NOT NULL COMMENT 'COSTO DE TINTA PARA 1 MILLAR 61*86' ,  
    `FMAQUICOSTO_BARNIZ72` DECIMAL(10,5) NOT NULL COMMENT 'COSTO DE BARNIZ PARA 1 MILLAR 72*102' , 
    `FMAQUICOSTO_BARNIZ61` DECIMAL(10,6) NOT NULL COMMENT 'COSTO DE BARNIZ PARA 1 MILLAR 61*86' ,  
    `FMAQUICOSTOP1` INT NOT NULL COMMENT 'AMORITZACION P1' ,  
    `FMAQUICOSTOP2` INT NOT NULL COMMENT 'AMORTIZACION P2' ,  
    
    
    CONSTRAINT PK_FMAQUI PRIMARY KEY (`FMAQUICODIGO`)

) ENGINE = INNODB CHARSET=utf8 COLLATE utf8_general_ci COMMENT = 'REGISTRO DE TABLA F1810 MAQUINA (FMAQUI)'; 

-- *****************************************************
-- Entidad Registro de Tabla F1810 INSUMO  [FINSU]
-- *****************************************************


CREATE TABLE `sistemact`.`F1810_INSU` ( 
    `FINSUCODIGO` INT NOT NULL AUTO_INCREMENT COMMENT 'CODIGO DE LA FORMULA F1810 INSUMO' , 
    `USUACODIGO` varchar(4) NOT NULL COMMENT 'CODIGO DEL USUARIO DE ACTUALIZACION' , 
    `FINSUFECHA_MODIFICADO` DATE NOT NULL COMMENT 'FECHA DE MODIFICACION DE LA FORMULA' , 
    `FINSUCAMBIO` DECIMAL(10,3) NOT NULL COMMENT 'TIPO DE CAMBIO' , 
    `FINSUFACTOR` DECIMAL(10,3) NOT NULL COMMENT 'FACTOR SOBRE COSTOS DIRECTOS DE SERVICIOS' , 
    `FINSUCOSTO_MILSO`DECIMAL(10,4) NOT NULL COMMENT 'COST/H MILSOLCISTA $' ,
    `FINSUCOSTOCH1` DECIMAL(10,4) NOT NULL COMMENT 'CHINESE - KG DE COUCHE 90 GRS' , 
    `FINSUCOSTOCH2` DECIMAL(10,4) NOT NULL COMMENT 'CHINESE - KG DE COUCHE 100-250 GRS' , 
    `FINSUCOSTOCH3` DECIMAL(10,4) NOT NULL COMMENT 'CHINESE - KG DE COUCHE 300-350 GRS' , 
    `FINSUCOSTOCH4` DECIMAL(10,4) NOT NULL COMMENT 'CHINESE - KG DE BOND 75-150 GRS' , 
    `FINSUCOSTOCH5` DECIMAL(10,4) NOT NULL COMMENT 'CHINESE - KG DE BOND 56 GRS' , 
    `FINSUCOSTOCH6` DECIMAL(10,4) NOT NULL COMMENT 'CHINESE - KG. DE GRAPHICS RB CAL 12 205 GRS' , 
    `FINSUCOSTOCH7` DECIMAL(10,4) NOT NULL COMMENT 'CHINESE - KG. DE GRAPHICS RB CAL 14-15 225-240 GRS' , 
    `FINSUCOSTOCH8` DECIMAL(10,4) NOT NULL COMMENT 'CHINESE - KG. MAULE GRAPHICS RB CAL 16 O 286 UP GRS' , 
    `FINSUCOSTOCH9` DECIMAL(10,4) NOT NULL COMMENT 'CHINESE - FOLKOTE' , 
    `FINSUCOSTOCH10` DECIMAL(10,4) NOT NULL COMMENT 'CHINESE - DUPLEX DE GRAMAJE MENOR A 286 GRS' , 
    `FINSUCOSTOCH11` DECIMAL(10,4) NOT NULL COMMENT 'CHINESE - AUTOCOPIATIVO: PESO PROMEDIO DE 53 GRS Y PRECIO DEL MAS ALTO CFB' , 
    `FINSUCOSTOCH12` DECIMAL(10,4) NOT NULL COMMENT 'CHINESE - CARTULINA LYNER' , 
    `FINSUCOSTOCH13` DECIMAL(10,4) NOT NULL COMMENT 'CHINESE - PAPEL PERIODICO' , 
    `FINSUCOSTOCH14` DECIMAL(10,4) NOT NULL COMMENT 'CHINESE - ADHESIVO P4' ,
    `FINSUCOSTOQU1` DECIMAL(10,4) NOT NULL COMMENT 'QUALITY - KG DE COUCHE 90 GRS' , 
    `FINSUCOSTOQU2` DECIMAL(10,4) NOT NULL COMMENT 'QUALITY - KG DE COUCHE 100-250 GRS' ,
    `FINSUCOSTOQU3` DECIMAL(10,4) NOT NULL COMMENT 'QUALITY - KG DE COUCHE 300-350 GRS' ,
    `FINSUCOSTODPLAXH1` DECIMAL(10,3) NOT NULL COMMENT 'TIEMPO X MANTENIMIENTO	' ,
    `FINSUCOSTODPLAXH2` DECIMAL(10,3) NOT NULL COMMENT 'DEPRECIACION' ,
    `FINSUCOSTODPLAXH3` DECIMAL(10,3) NOT NULL COMMENT 'GASTO MANTENIMIENTO' ,
    `FINSUCOSTODPLAXH4` DECIMAL(10,3) NOT NULL COMMENT 'MERMA 10%' ,
    `FINSUCOSTODPLAXH5` DECIMAL(10,3) NOT NULL COMMENT 'PRODUCTO AUXILIAR' ,
    `FINSUCOSTODPLAXH6` DECIMAL(10,3) NOT NULL COMMENT 'DECIMAL 3' ,
    `FINSUCOSTOPLACAGTO1` DECIMAL(10,3) NOT NULL COMMENT 'COSTO DIRECTO DE LA GTO ' ,
    `FINSUCOSTOPLACAGTO2` DECIMAL(10,3) NOT NULL COMMENT 'TIEMPO DE UN JUEGO DE PLACAS DE LA GTO' ,
    `FINSUCOSTOPLACASM1` DECIMAL(10,3) NOT NULL COMMENT 'COSTO DIRECTO DE LA SM' ,
    `FINSUCOSTOPLACASM2` DECIMAL(10,3) NOT NULL COMMENT 'TIEMPO DE UN JUEGO DE PLACAS DE LA SM' ,
    `FINSUCOSTOPLACAR7001` DECIMAL(10,3) NOT NULL COMMENT 'COSTO DIRECTO DE LA R700' ,
    `FINSUCOSTOPLACAR7002` DECIMAL(10,3) NOT NULL COMMENT 'TIEMPO DE UN JUEGO DE PLACAS DE LA ROLAND 700' ,
    `FINSUCOSTOOPERARIOSO` DECIMAL(10,3) NOT NULL COMMENT 'PAGO MENSUAL DE UN OPERARIO' ,
    `FINSUCOSTOOPERARIOHR` DECIMAL(10,3) NOT NULL COMMENT 'HORAS MENSUAL DE UN OPERARIO' ,
    `FINSUITEMAGREGADO1` DECIMAL(10,6) NOT NULL COMMENT 'VALOR AGREGADO DEL ITEM UV-B' ,
    `FINSUITEMAGREGADO2` DECIMAL(10,6) NOT NULL COMMENT 'VALOR AGREGADO DEL ITEM OFFB' ,
    `FINSUITEMAGREGADO3` DECIMAL(10,6) NOT NULL COMMENT 'VALOR AGREGADO DEL ITEM OFFM' ,
    `FINSUITEMAGREGADO4` DECIMAL(10,6) NOT NULL COMMENT 'VALOR AGREGADO DEL ITEM ACRB' ,
    `FINSUITEMAGREGADO5` DECIMAL(10,6) NOT NULL COMMENT 'VALOR AGREGADO DEL ITEM ACRM' ,
    `FINSUITEM1` DECIMAL(10,6)  NULL COMMENT 'PRECIO UV-B' ,
    `FINSUITEM2` DECIMAL(10,6)  NULL COMMENT 'PRECIO UV-B-2C	' , 
    `FINSUITEM3` DECIMAL(10,6)  NULL COMMENT 'PRECIO UV-M' ,
    `FINSUITEM4` DECIMAL(10,6)  NULL COMMENT 'PRECIO UV-M-2C' ,
    `FINSUITEM5` DECIMAL(10,6)  NULL COMMENT 'PRECIO UVSB' ,
    `FINSUITEM6` DECIMAL(10,6)  NULL COMMENT 'PRECIO UVSB-2C' ,
    `FINSUITEM7` DECIMAL(10,6)  NULL COMMENT 'PRECIO UVSM' ,
    `FINSUITEM8` DECIMAL(10,6)  NULL COMMENT 'PRECIO UVSM-2C	' ,
    `FINSUITEM9` DECIMAL(10,6)  NULL COMMENT 'PRECIO OFFB' ,
    `FINSUITEM10` DECIMAL(10,6)  NULL COMMENT 'PRECIO OFFB-2C' ,
    `FINSUITEM11` DECIMAL(10,6)  NULL COMMENT 'PRECIO OFFM' ,
    `FINSUITEM12` DECIMAL(10,6)  NULL COMMENT 'PRECIO OFFM-2C' ,
    `FINSUITEM13` DECIMAL(10,6)  NULL COMMENT 'PRECIO ACRB' ,
    `FINSUITEM14` DECIMAL(10,6)  NULL COMMENT 'PRECIO ACRB-2C	' ,
    `FINSUITEM15` DECIMAL(10,6)  NULL COMMENT 'PRECIO ACRM' ,
    `FINSUITEM16` DECIMAL(10,6)  NULL COMMENT 'PRECIO ACRM-2C' ,
    `FINSUITEM17` DECIMAL(10,6)  NULL COMMENT 'PRECIO PL-B' ,
    `FINSUITEM18` DECIMAL(10,6)  NULL COMMENT 'PRECIO PL-B-2C' ,
    `FINSUITEM19` DECIMAL(10,6)  NULL COMMENT 'PRECIO PL-M' ,
    `FINSUITEM20` DECIMAL(10,6)  NULL COMMENT 'PRECIO PL-M-2C' ,
    `FINSUITEM21` DECIMAL(10,6)  NULL COMMENT 'PRECIO PL-H' ,
    `FINSUITEM22` DECIMAL(10,6)  NULL COMMENT 'PRECIO PL-H-2C' ,
    `FINSUITEM23` DECIMAL(10,6)  NULL COMMENT 'PRECIO ESCH' ,
    `FINSUITEM24`  DECIMAL(10,6)  NULL COMMENT 'PRECIO ESCH-2C' ,
    `FINSUITEM25` DECIMAL(10,6)  NULL COMMENT 'PRECIO HOST' ,
    `FINSUITEM26` DECIMAL(10,6)  NULL COMMENT 'PRECIO HOST-2C' ,
    `FINSUITEM27` DECIMAL(10,6)  NULL COMMENT 'COSTO UV-B' ,
    `FINSUITEM28` DECIMAL(10,6)  NULL COMMENT 'COSTO UV-B-2C' ,
    `FINSUITEM29` DECIMAL(10,6)  NULL COMMENT 'COSTO UV-M' ,
    `FINSUITEM30` DECIMAL(10,6)  NULL COMMENT 'COSTO UV-M-2C' ,
    `FINSUITEM31` DECIMAL(10,6)  NULL COMMENT 'COSTO UVSB' ,
    `FINSUITEM32` DECIMAL(10,6)  NULL COMMENT 'COSTO UVSB-2C' ,
    `FINSUITEM33` DECIMAL(10,6)  NULL COMMENT 'COSTO UVSM' ,
    `FINSUITEM34` DECIMAL(10,6)  NULL COMMENT 'COSTO UVSM-2C' ,
    `FINSUITEM35` DECIMAL(10,6)  NULL COMMENT 'COSTO OFFB' ,
    `FINSUITEM36` DECIMAL(10,6)  NULL COMMENT 'COSTO OFFB-2C' ,
    `FINSUITEM37` DECIMAL(10,6)  NULL COMMENT 'COSTO OFFM' ,
    `FINSUITEM38` DECIMAL(10,6)  NULL COMMENT 'COSTO OFFM-2C' ,
    `FINSUITEM39` DECIMAL(10,6)  NULL COMMENT 'COSTO ACRB' ,
    `FINSUITEM40` DECIMAL(10,6)  NULL COMMENT 'COSTO ACRB-2C' ,
    `FINSUITEM41` DECIMAL(10,6)  NULL COMMENT 'COSTO ACRM' ,
    `FINSUITEM42` DECIMAL(10,6)  NULL COMMENT 'COSTO ACRM-2C' ,
    `FINSUITEM43` DECIMAL(10,6)  NULL COMMENT 'COSTO PL-B' ,
    `FINSUITEM44` DECIMAL(10,6)  NULL COMMENT 'COSTO PL-B-2C' ,
    `FINSUITEM45` DECIMAL(10,6)  NULL COMMENT 'COSTO PL-M' ,
    `FINSUITEM46` DECIMAL(10,6)  NULL COMMENT 'COSTO PL-M-2C' ,
    `FINSUITEM47` DECIMAL(10,6)  NULL COMMENT 'COSTO PL-H' ,
    `FINSUITEM48` DECIMAL(10,6)  NULL COMMENT 'COSTO PL-H-2C' ,
    `FINSUITEM49` DECIMAL(10,6)  NULL COMMENT 'COSTO ESCH' ,
    `FINSUITEM50` DECIMAL(10,6)  NULL COMMENT 'COSTO ESCH-2C' ,
    `FINSUITEM51` DECIMAL(10,6)  NULL COMMENT 'COSTO HOST' ,
    `FINSUITEM52` DECIMAL(10,6)  NULL COMMENT 'COSTO HOST-2C' ,
    `FINSUITEM53` DECIMAL(10,6)  NULL COMMENT 'COSTO INSUMO POR MT2 - UV-B' ,
    `FINSUITEM54` DECIMAL(10,6)  NULL COMMENT 'COSTO INSUMO POR MT2 - UV-B-2C' ,
    `FINSUITEM55` DECIMAL(10,6)  NULL COMMENT 'COSTO INSUMO POR MT2 - UV-M' ,
    `FINSUITEM56` DECIMAL(10,6)  NULL COMMENT 'COSTO INSUMO POR MT2 - UV-M-2C' ,
    `FINSUITEM57` DECIMAL(10,6)  NULL COMMENT 'COSTO INSUMO POR MT2 - UVSB' ,
    `FINSUITEM58` DECIMAL(10,6)  NULL COMMENT 'COSTO INSUMO POR MT2 - UVSB-2C' ,
    `FINSUITEM59` DECIMAL(10,6)  NULL COMMENT 'COSTO INSUMO POR MT2 - UVSM' ,
    `FINSUITEM60` DECIMAL(10,6)  NULL COMMENT 'COSTO INSUMO POR MT2 - UVSM-2C' ,
    `FINSUITEM61` DECIMAL(10,6)  NULL COMMENT 'COSTO INSUMO POR MT2 - OFFB' ,
    `FINSUITEM62` DECIMAL(10,6)  NULL COMMENT 'COSTO INSUMO POR MT2 - OFFB-2C' ,
    `FINSUITEM63` DECIMAL(10,6)  NULL COMMENT 'COSTO INSUMO POR MT2 - OFFM' ,
    `FINSUITEM64` DECIMAL(10,6)  NULL COMMENT 'COSTO INSUMO POR MT2 - OFFM-2C' ,
    `FINSUITEM65` DECIMAL(10,6)  NULL COMMENT 'COSTO INSUMO POR MT2 - ACRB' ,
    `FINSUITEM66` DECIMAL(10,6)  NULL COMMENT 'COSTO INSUMO POR MT2 - ACRB-2C' ,
    `FINSUITEM67` DECIMAL(10,6)  NULL COMMENT 'COSTO INSUMO POR MT2 - ACRM' ,
    `FINSUITEM68` DECIMAL(10,6)  NULL COMMENT 'COSTO INSUMO POR MT2 - ACRM-2C' ,
    `FINSUITEM69` DECIMAL(10,6)  NULL COMMENT 'COSTO INSUMO POR MT2 - PL-B' ,
    `FINSUITEM70` DECIMAL(10,6)  NULL COMMENT 'COSTO INSUMO POR MT2 - PL-B-2C' ,
    `FINSUITEM71` DECIMAL(10,6)  NULL COMMENT 'COSTO INSUMO POR MT2 - PL-M' ,
    `FINSUITEM72` DECIMAL(10,6)  NULL COMMENT 'COSTO INSUMO POR MT2 - PL-M-2C' ,
    `FINSUITEM73` DECIMAL(10,6)  NULL COMMENT 'COSTO INSUMO POR MT2 - PL-H' ,
    `FINSUITEM74` DECIMAL(10,6)  NULL COMMENT 'COSTO INSUMO POR MT2 - PL-H-2C' ,
    `FINSUITEM75` DECIMAL(10,6)  NULL COMMENT 'COSTO INSUMO POR MT2 - ESCH' ,
    `FINSUITEM76` DECIMAL(10,6)  NULL COMMENT 'COSTO INSUMO POR MT2 - ESCH-2C' ,
    `FINSUITEM77` DECIMAL(10,6)  NULL COMMENT 'COSTO INSUMO POR MT2 - HOST' ,
    `FINSUITEM78` DECIMAL(10,6)  NULL COMMENT 'COSTO INSUMO POR MT2 - HOST-2C' ,    
    `FINSUITEM79` VARCHAR(30)  NULL COMMENT 'INSUMO UV-B' ,
    `FINSUITEM80` VARCHAR(30)  NULL COMMENT 'INSUMO UV-B-2C' ,
    `FINSUITEM81` VARCHAR(30)  NULL COMMENT 'INSUMO UV-M' ,
    `FINSUITEM82` VARCHAR(30)  NULL COMMENT 'INSUMO UV-M-2C' ,
    `FINSUITEM83` VARCHAR(30)  NULL COMMENT 'INSUMO UVSB' ,
    `FINSUITEM84` VARCHAR(30)  NULL COMMENT 'INSUMO UVSB-2C' ,
    `FINSUITEM85` VARCHAR(30)  NULL COMMENT 'INSUMO UVSM' ,
    `FINSUITEM86` VARCHAR(30)  NULL COMMENT 'INSUMO UVSM-2C' ,
    `FINSUITEM87` VARCHAR(30)  NULL COMMENT 'INSUMO OFFB' ,
    `FINSUITEM88` VARCHAR(30)  NULL COMMENT 'INSUMO OFFB-2C' ,
    `FINSUITEM89` VARCHAR(30)  NULL COMMENT 'INSUMO OFFM' ,
    `FINSUITEM90` VARCHAR(30)  NULL COMMENT 'INSUMO OFFM-2C' ,
    `FINSUITEM91` VARCHAR(30)  NULL COMMENT 'INSUMO ACRB' ,
    `FINSUITEM92` VARCHAR(30)  NULL COMMENT 'INSUMO ACRB-2C' ,
    `FINSUITEM93` VARCHAR(30)  NULL COMMENT 'INSUMO ACRM' ,
    `FINSUITEM94` VARCHAR(30)  NULL COMMENT 'INSUMO ACRM-2C' ,
    `FINSUITEM95` VARCHAR(30)  NULL COMMENT 'INSUMO PL-B' ,
    `FINSUITEM96` VARCHAR(30)  NULL COMMENT 'INSUMO PL-B-2C' ,
    `FINSUITEM97` VARCHAR(30)  NULL COMMENT 'INSUMO PL-M' ,
    `FINSUITEM98` VARCHAR(30)  NULL COMMENT 'INSUMO PL-M-2C' ,
    `FINSUITEM99` VARCHAR(30)  NULL COMMENT 'INSUMO PL-H' ,
    `FINSUITEM100` VARCHAR(30)  NULL COMMENT 'INSUMO PL-H-2C' ,
    `FINSUITEM101` VARCHAR(30)  NULL COMMENT 'INSUMO ESCH' ,
    `FINSUITEM102` VARCHAR(30)  NULL COMMENT 'INSUMO ESCH-2C' ,
    `FINSUITEM103` VARCHAR(30)  NULL COMMENT 'INSUMO HOST' ,
    `FINSUITEM104` VARCHAR(30)  NULL COMMENT 'INSUMO HOST-2C' ,
    `FINSUITEM105` DECIMAL(10,6)  NULL COMMENT 'PRECIO INSUMO UV-B' ,
    `FINSUITEM106` DECIMAL(10,6)  NULL COMMENT 'PRECIO INSUMO UV-B-2C' , 
    `FINSUITEM107` DECIMAL(10,6)  NULL COMMENT 'PRECIO INSUMO UV-M' ,
    `FINSUITEM108` DECIMAL(10,6)  NULL COMMENT 'PRECIO INSUMO UV-M-2C' ,
    `FINSUITEM109` DECIMAL(10,6)  NULL COMMENT 'PRECIO INSUMO UVSB' ,
    `FINSUITEM110` DECIMAL(10,6)  NULL COMMENT 'PRECIO INSUMO UVSB-2C' ,
    `FINSUITEM111` DECIMAL(10,6)  NULL COMMENT 'PRECIO INSUMO UVSM' ,
    `FINSUITEM112` DECIMAL(10,6)  NULL COMMENT 'PRECIO INSUMO UVSM-2C	' ,
    `FINSUITEM113` DECIMAL(10,6)  NULL COMMENT 'PRECIO INSUMO OFFB' ,
    `FINSUITEM114` DECIMAL(10,6)  NULL COMMENT 'PRECIO INSUMO OFFB-2C' ,
    `FINSUITEM115` DECIMAL(10,6)  NULL COMMENT 'PRECIO INSUMO OFFM' ,
    `FINSUITEM116` DECIMAL(10,6)  NULL COMMENT 'PRECIO INSUMO OFFM-2C' ,
    `FINSUITEM117` DECIMAL(10,6)  NULL COMMENT 'PRECIO INSUMO ACRB' ,
    `FINSUITEM118` DECIMAL(10,6)  NULL COMMENT 'PRECIO INSUMO ACRB-2C' ,
    `FINSUITEM119` DECIMAL(10,6)  NULL COMMENT 'PRECIO INSUMO ACRM' ,
    `FINSUITEM120` DECIMAL(10,6)  NULL COMMENT 'PRECIO INSUMO ACRM-2C' ,
    `FINSUITEM121` DECIMAL(10,6)  NULL COMMENT 'PRECIO INSUMO PL-B' ,
    `FINSUITEM122` DECIMAL(10,6)  NULL COMMENT 'PRECIO INSUMO PL-B-2C' ,
    `FINSUITEM123` DECIMAL(10,6)  NULL COMMENT 'PRECIO INSUMO PL-M' ,
    `FINSUITEM124` DECIMAL(10,6)  NULL COMMENT 'PRECIO INSUMO PL-M-2C' ,
    `FINSUITEM125` DECIMAL(10,6)  NULL COMMENT 'PRECIO INSUMO PL-H' ,
    `FINSUITEM126` DECIMAL(10,6)  NULL COMMENT 'PRECIO INSUMO PL-H-2C' ,
    `FINSUITEM127` DECIMAL(10,6)  NULL COMMENT 'PRECIO INSUMO ESCH' ,
    `FINSUITEM128`  DECIMAL(10,6)  NULL COMMENT 'PRECIO INSUMO ESCH-2C' ,
    `FINSUITEM129` DECIMAL(10,6)  NULL COMMENT 'PRECIO INSUMO HOST' ,
    `FINSUITEM130` DECIMAL(10,6)  NULL COMMENT 'PRECIO INSUMO HOST-2C' ,    
    `FINSUITEM131` DECIMAL(10,6)  NULL COMMENT 'REND X MT2 UV-B' ,
    `FINSUITEM132` DECIMAL(10,6)  NULL COMMENT 'REND X MT2 UV-B-2C' , 
    `FINSUITEM133` DECIMAL(10,6)  NULL COMMENT 'REND X MT2 UV-M' ,
    `FINSUITEM134` DECIMAL(10,6)  NULL COMMENT 'REND X MT2 UV-M-2C' ,
    `FINSUITEM135` DECIMAL(10,6)  NULL COMMENT 'REND X MT2 UVSB' ,
    `FINSUITEM136` DECIMAL(10,6)  NULL COMMENT 'REND X MT2 UVSB-2C' ,
    `FINSUITEM137` DECIMAL(10,6)  NULL COMMENT 'REND X MT2 UVSM' ,
    `FINSUITEM138` DECIMAL(10,6)  NULL COMMENT 'REND X MT2 UVSM-2C' ,
    `FINSUITEM139` DECIMAL(10,6)  NULL COMMENT 'REND X MT2 OFFB' ,
    `FINSUITEM140` DECIMAL(10,6)  NULL COMMENT 'REND X MT2 OFFB-2C' ,
    `FINSUITEM141` DECIMAL(10,6)  NULL COMMENT 'REND X MT2 OFFM' ,
    `FINSUITEM142` DECIMAL(10,6)  NULL COMMENT 'REND X MT2 OFFM-2C' ,
    `FINSUITEM143` DECIMAL(10,6)  NULL COMMENT 'REND X MT2 ACRB' ,
    `FINSUITEM144` DECIMAL(10,6)  NULL COMMENT 'REND X MT2 ACRB-2C' ,
    `FINSUITEM145` DECIMAL(10,6)  NULL COMMENT 'REND X MT2 ACRM' ,
    `FINSUITEM146` DECIMAL(10,6)  NULL COMMENT 'REND X MT2 ACRM-2C' ,
    `FINSUITEM147` DECIMAL(10,6)  NULL COMMENT 'REND X MT2 PL-B' ,
    `FINSUITEM148` DECIMAL(10,6)  NULL COMMENT 'REND X MT2 PL-B-2C' ,
    `FINSUITEM149` DECIMAL(10,6)  NULL COMMENT 'REND X MT2 PL-M' ,
    `FINSUITEM150` DECIMAL(10,6)  NULL COMMENT 'REND X MT2 PL-M-2C' ,
    `FINSUITEM151` DECIMAL(10,6)  NULL COMMENT 'REND X MT2 PL-H' ,
    `FINSUITEM152` DECIMAL(10,6)  NULL COMMENT 'REND X MT2 PL-H-2C' ,
    `FINSUITEM153` DECIMAL(10,6)  NULL COMMENT 'REND X MT2 ESCH' ,
    `FINSUITEM154`  DECIMAL(10,6)  NULL COMMENT 'REND X MT2 ESCH-2C' ,
    `FINSUITEM155` DECIMAL(10,6)  NULL COMMENT 'REND X MT2 HOST' ,
    `FINSUITEM156` DECIMAL(10,6)  NULL COMMENT 'REND X MT2 HOST-2C' ,
    
    
    CONSTRAINT PK_FINSU PRIMARY KEY (`FINSUCODIGO`)

) ENGINE = INNODB CHARSET=utf8 COLLATE utf8_general_ci COMMENT = 'REGISTRO DE TABLA F1810 INSUMOS (FINSU)'; 


-- *****************************************************
-- Entidad Registro de Contrato [CONTR]
-- *****************************************************


DROP TABLE IF EXISTS `CONTRATO`;
CREATE TABLE IF NOT EXISTS `CONTRATO` ( 
    `CONTRCODIGO` varchar(4) NOT NULL  COMMENT 'CODIGO DEL CONTRATO DEL PERSONAL',
    `PERSCODIGO` int(11) NOT NULL  COMMENT 'CODIGO DEL PERSONAL',
    `ESTCODIGO` int(11) NOT NULL COMMENT 'ESTADO DEL CONTRATO DEL PERSONAL',
    `CONTRINGRESO_PLANILLA` date  NOT NULL  COMMENT 'FECHA DE INGRESO A PLANILLA DEL PERSONAL',
    `EMPCODIGO` varchar(2) NOT NULL COMMENT 'CODIGO DE LA EMPRESA',
    
    PRIMARY KEY (`CONTRCODIGO`)
    
) ENGINE=INNODB DEFAULT CHARSET=utf8 COMMENT='REGISTRO DE CONTRATO (CONTR)';

-- *****************************************************
-- Entidad Registro de Detalle Contrato [DETCONTR]
-- *****************************************************


DROP TABLE IF EXISTS `DETALLE_CONTRATO`;
CREATE TABLE IF NOT EXISTS `DETALLE_CONTRATO` (
    `DETCONTRCODIGO` varchar(6) NOT NULL  COMMENT 'CODIGO DEL CONTRATO DEL PERSONAL',
    `DETCONTRFECHA_CONTRATACION` date  NOT NULL  COMMENT 'FECHA DE CONTRATACION DEL PERSONAL',
    `DETCONTRTIEMPO` int(11)  NULL  COMMENT 'TIEMPO DE CONTRATO DEL PERSONAL EN MESES',   
    `DETCONTRDIAS_VACA` int(11)  NULL  COMMENT 'DIAS DE VACACIONES EN EL CONTRATO DEL PERSONAL',
    `CONTRCODIGO` varchar(4) NOT NULL  COMMENT 'CODIGO DEL CONTRATO DEL PERSONAL',
   
    PRIMARY KEY (`DETCONTRCODIGO`)
    
) ENGINE=INNODB DEFAULT CHARSET=utf8 COMMENT='REGISTRO DE DETALLE DEL CONTRATO (DETCONTR)';



-- ********************************************************
-- Entidad Registro de Vacaciones del Personal [VACAPERS]
-- ********************************************************


DROP TABLE IF EXISTS `VACACIONES`;
CREATE TABLE IF NOT EXISTS `VACACIONES` (
    `VACAPERSCODIGO` varchar(4)  NOT NULL  COMMENT 'CODIGO DE VACACIONES DEL PERSONAL',
    `DETCONTRCODIGO` varchar(6) NOT NULL  COMMENT 'CODIGO DEL CONTRATO DEL PERSONAL',
    `VACAPERSNUMERO` int(11) NOT NULL  COMMENT 'NUMERO DE ORDEN DE VACACIONES DEL PERSONAL',
    `VACAEFECTIVAS` int(11) NOT NULL COMMENT 'DIAS EFECTIVOS DE LAS VACACIONES',

    PRIMARY KEY (`VACAPERSCODIGO`)
  
) ENGINE=INNODB DEFAULT CHARSET=utf8 COMMENT='VACACIONES DE PERSONAL (VACAPERS)';


-- ********************************************************
-- Entidad Registro de Detalles Vacaciones del Personal [DETVACAPERS]
-- ********************************************************


DROP TABLE IF EXISTS `DETALLE_VACACIONES`;
CREATE TABLE IF NOT EXISTS `DETALLE_VACACIONES` (
    `DETVACAPERSCODIGO` varchar(7) NOT NULL  COMMENT 'CODIGO DE VACACIONES DEL PERSONAL',
    `DETVACAPERSINICIO` date  NULL  COMMENT 'FECHA DE INICIO DE VACACIONES DEL PERSONAL',
    `DETVACAPERSDIAS` int(11)  NOT NULL  COMMENT 'DIAS DE VACACIONES DEL PERSONAL',
    `ESTCODIGO` int(11) NOT NULL COMMENT 'ESTADO DESIGNADO DE LAS VACACIONES DEL PERSONAL',
    `DETVACAPERSOBS` varchar(30)  NULL  COMMENT 'OBSERVACIONES DE LAS VACACIONES DEL PERSONAL',
    `VACAPERSCODIGO` varchar(4)  NOT NULL  COMMENT 'CODIGO DE VACACIONES DEL PERSONAL',    
    
    PRIMARY KEY (`DETVACAPERSCODIGO`)
    
) ENGINE=INNODB DEFAULT CHARSET=utf8 COMMENT='REGISTRO DE DETALLE VACACIONES DEL PERSONAL (DETVACAPERS)';























